### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by ghost** [thrunduil/cyclic_rc#1]
https://github.com/thrunduil/cyclic_rc/blob/8430210b80d2dc28c1212cbf1d04a9f32e37ae82/src/cyclic_rc/include/cyclic_rc/details/obj_count.inl#L147

why not 
`delete s;`

**Comment by thrunduil** [comment]
At this moment a slot cannot be destroyed, might be needed later. Take for example a cycle A -> B -> A, and a destructor of A is called. Object A cannot be destroyed, since it can be accessed by a destructor of the object B.  Memory is freed after calling all destructors.
